### ISSUE TITLE
Keep __bindingAddress when redirecting after login

### ISSUE THREAD

**Issue by brunoabreu** [vtex-apps/login#178]
**Is your feature request related to a problem? Please describe.**
We are handling multiple bindings in `{tenant}.myvtex.com` by keeping a persistent query string `__bindingAddress`. But after login in using `/login?__bindingAddress={someAddress}` you will be redirected to `/` with no binding information, ending up in the default binding.

**Describe the solution you'd like**
Keep `__bindingAddress` query string when redirecting after login.

**Describe alternatives you've considered**
None. ¯\_(ツ)_/¯

**Additional context**
You can reach me for more details and examples.

**Comment by rnbez** [comment]
Hi @brunoabreu . Pretty sure #169 solves this problem.

**Comment by brunoabreu** [comment]
Unfortunately, it won't solve my problem. ☹️

It happens here:
https://github.com/vtex-apps/login/blob/5abbcb102490a2b6ebd73023aafbdeb89ad59f0a/react/components/LoginContent.js#L175-L176

**Comment by rnbez** [comment]
I'm closing this issue since we discussed this internally and will implement this feature asap.
