### ISSUE TITLE
defaultOption prop not working.

### ISSUE THREAD

**Issue by JNussens** [vtex-apps/login#197]
**Describe the bug**
When trying to render the login-content with the social providers and *email and password fields already open*, using the `defaultOption` prop, the component refuses to change it's content (this was working fine until the latest few releases. We really need this working again and fast. Can you guys help us with that?

**To Reproduce**
1. Use vtex init to initialize a fresh app
2. Go to the blocks and try to add the following:
```
"login-content#test": {
    "props": {
      "defaultOption": 1
    }
  },
```
3. The login content does not change, it does not work at all. [ERROR]

**Expected behavior**
It should render both the social providers as well as the *OPEN STATE* login form (email and password)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This problem started last week, if it helps.

**Comment by rafarubim** [comment]
Hi @JNussens! I'm having trouble understanding/reproducing the problem through these steps. Also, I couldn't find any release related to this last week.
But from what I read, maybe disabling `isInitialScreenOptionOnly` will fix your problem. Have you tried this in your `blocks.json`?
```
"login-content#test": {
    "props": {
      "isInitialScreenOptionOnly": false,
      "defaultOption": 1
    }
  },
```
