### ISSUE TITLE
Cannot read property 'accessKeyAuthentication' of undefined

### ISSUE THREAD

**Issue by MatheusR42** [vtex-apps/login#63]
![image 4](https://user-images.githubusercontent.com/16908590/45574465-839b1380-b846-11e8-89b5-0bc23ccddba6.png)

O erro acontece quando o modulo Profile System cai no http://healthcheck.vtex.com/. Sei que não há muito o que fazer nesses casos, mas esse erro está fazendo todo o componente pai sumir junto.

**Comment by brunojdo** [comment]
Fixed
