### ISSUE TITLE
Novo valor na props do LoginContent

### ISSUE THREAD

**Issue by felipe-ssilva** [vtex-apps/login#69]
Qual a possibilidade de termos um novo valor na props, para alterarmos o texto do campo em vermelho?

![capturar](https://user-images.githubusercontent.com/4562886/46384006-c1db6400-c689-11e8-80d5-d6d501ba316d.JPG)

Hoje sem essa opção, uma forma de "driblar" isso seria com um :before/:after no CSS ou sobrescrever com js.

**Comment by brunojdo** [comment]
Oi Felipe, podemos fazer isso pelo storefront. Na versão 2.x do Login

**Comment by felipe-ssilva** [comment]
Obrigado, @brunojdo
