### ISSUE TITLE
Follow the `returnUrl` param

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/login#96]
**Is your feature request related to a problem? Please describe.**
The app should respect the returnUrl param and follow that link instead of returning to the home page.
Also, the returnUrl should keep the full path (it removes `#/orders` from the url for example).

**Describe the solution you'd like**
returnUrl should work as the name says, an url to be returned to after a successful login.

**Describe alternatives you've considered**
N/A

**Additional context**
Try to access https://avanti.myvtex.com/account#/orders (to redirect to the MyOrders page)
That will send you to https://avanti.myvtex.com/login?returnUrl=/account (it lost the `#/orders`)
Then after logging in, it returns to the home page, but it should have gone to the MyOrders page, `/account#/orders`

**Comment by rnbez** [comment]
@hapoza I believe this has been fixed couple days ago. Can you validate it?
